name: Auto Release from Main Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate timestamp tag
      run: |
        export TZ=Asia/Seoul
        TAG_NAME=v$(date +'%Y.%m.%d.%H%M%S')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: "Automated Release ${{ env.TAG_NAME }}"
        body: "Release triggered from push to main"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Go image
      uses: docker/build-push-action@v5
      with:
        context: ./go
        file: ./go/Dockerfile
        push: true
        tags: |
          xxng/kafka-test-go:${{ env.TAG_NAME }}
          xxng/kafka-test-go:latest

    - name: Build and Push Django image
      uses: docker/build-push-action@v5
      with:
        context: ./apiserver
        file: ./apiserver/Dockerfile
        push: true
        tags: |
          xxng/django-apiserver:${{ env.TAG_NAME }}
          xxng/django-apiserver:latest


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Django image to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        context: ./apiserver
        file: ./apiserver/Dockerfile
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ env.TAG_NAME }}
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
