name: Auto Release from Main Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  release-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate timestamp tag
      run: |
        export TZ=Asia/Seoul
        TAG_NAME=v$(date +'%Y.%m.%d.%H%M%S')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: "Automated Release ${{ env.TAG_NAME }}"
        body: "Release triggered from push to main"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image with tag
      uses: docker/build-push-action@v5
      with:
        context: ./go
        file: ./go/Dockerfile
        push: true
        tags: |
          xxng/kafka-test-go:${{ env.TAG_NAME }}
          xxng/kafka-test-go:latest

    # ✅ Django (apiserver) 이미지 빌드 & 푸시
    - name: Build and Push Django image
      uses: docker/build-push-action@v5
      with:
        context: ./apiserver
        file: ./apiserver/Dockerfile
        push: true
        tags: |
          xxng/django-apiserver:${{ env.TAG_NAME }}          
          xxng/django-apiserver:latest


    - name: Deploy Django to EC2
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2-key.pem
        chmod 600 ec2-key.pem

        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo docker pull xxng/django-apiserver:latest

          # 기존 컨테이너 정리
          sudo docker stop django-container || true
          sudo docker rm django-container || true

          # 새 컨테이너 실행 (포트 80으로 앱단에서 설정)
          sudo docker run -d \
            --name django-container \
            -p 80:80 \
            xxng/django-apiserver:latest
        EOF
